name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: chat_project.settings
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: chat_project.settings
        run: |
          pytest
